  DROP TABLE IF EXISTS lotoresults_12;
  CREATE TABLE lotoresults_12 
  (
    weekid  int(10) unsigned NOT NULL AUTO_INCREMENT,
    input1 double NOT NULL,
    input2 double NOT NULL,
    input3 double NOT NULL,
    input4 double NOT NULL,
    input5 double NOT NULL,
    input6 double NOT NULL,
    input7 double NOT NULL,
    input8 double NOT NULL,
    input9 double NOT NULL,
    input10 double NOT NULL,
    input11 double NOT NULL,
    input12 double NOT NULL,
    input13 double NOT NULL,
    input14 double NOT NULL,
    input15 double NOT NULL,
    input16 double NOT NULL,
    input17 double NOT NULL,
    input18 double NOT NULL,
    input19 double NOT NULL,
    input20 double NOT NULL,
    input21 double NOT NULL,
    input22 double NOT NULL,
    input23 double NOT NULL,
    input24 double NOT NULL,
    input25 double NOT NULL,
    input26 double NOT NULL,
    input27 double NOT NULL,
    input28 double NOT NULL,
    input29 double NOT NULL,
    input30 double NOT NULL,
    input31 double NOT NULL,
    input32 double NOT NULL,
    input33 double NOT NULL,
    input34 double NOT NULL,
    input35 double NOT NULL,
    input36 double NOT NULL,
    input37 double NOT NULL,
    input38 double NOT NULL,
    input39 double NOT NULL,
    input40 double NOT NULL,
    input41 double NOT NULL,
    input42 double NOT NULL,
    input43 double NOT NULL,
    input44 double NOT NULL,
    input45 double NOT NULL,
    input46 double NOT NULL,
    input47 double NOT NULL,
    input48 double NOT NULL,
    input49 double NOT NULL,
    
    ideal1 double NOT NULL,
    ideal2 double NOT NULL,
    ideal3 double NOT NULL,
    ideal4 double NOT NULL,
    ideal5 double NOT NULL,
    ideal6 double NOT NULL,
    ideal7 double NOT NULL,
    ideal8 double NOT NULL,
    ideal9 double NOT NULL,
    ideal10 double NOT NULL,
    ideal11 double NOT NULL,
    ideal12 double NOT NULL,
    ideal13 double NOT NULL,
    ideal14 double NOT NULL,
    ideal15 double NOT NULL,
    ideal16 double NOT NULL,
    ideal17 double NOT NULL,
    ideal18 double NOT NULL,
    ideal19 double NOT NULL,
    ideal20 double NOT NULL,
    ideal21 double NOT NULL,
    ideal22 double NOT NULL,
    ideal23 double NOT NULL,
    ideal24 double NOT NULL,
    ideal25 double NOT NULL,
    ideal26 double NOT NULL,
    ideal27 double NOT NULL,
    ideal28 double NOT NULL,
    ideal29 double NOT NULL,
    ideal30 double NOT NULL,
    ideal31 double NOT NULL,
    ideal32 double NOT NULL,
    ideal33 double NOT NULL,
    ideal34 double NOT NULL,
    ideal35 double NOT NULL,
    ideal36 double NOT NULL,
    ideal37 double NOT NULL,
    ideal38 double NOT NULL,
    ideal39 double NOT NULL,
    ideal40 double NOT NULL,
    ideal41 double NOT NULL,
    ideal42 double NOT NULL,
    ideal43 double NOT NULL,
    ideal44 double NOT NULL,
    ideal45 double NOT NULL,
    ideal46 double NOT NULL,
    ideal47 double NOT NULL,
    ideal48 double NOT NULL,
    ideal49 double NOT NULL,
    Primary key (weekid)  
  );

  DROP TABLE IF EXISTS lotoresults6_12;
  CREATE TABLE lotoresults6_12
  (
    weekid  int(10) unsigned NOT NULL AUTO_INCREMENT,
    input1 double NOT NULL,
    input2 double NOT NULL,
    input3 double NOT NULL,
    input4 double NOT NULL,
    input5 double NOT NULL,
    input6 double NOT NULL,
	ideal1 double NOT NULL,
    ideal2 double NOT NULL,
    ideal3 double NOT NULL,
    ideal4 double NOT NULL,
    ideal5 double NOT NULL,
    ideal6 double NOT NULL,
    ideal7 double NOT NULL,
    ideal8 double NOT NULL,
    ideal9 double NOT NULL,
    ideal10 double NOT NULL,
    ideal11 double NOT NULL,
    ideal12 double NOT NULL,
   
    Primary key (weekid)  
  );


LOAD DATA INFILE 'D:\\sayisalAi\\inp49_12li.csv' INTO TABLE lotoresults_12
  FIELDS TERMINATED BY ',' 
  LINES TERMINATED BY '\r\n'
IGNORE 1 LINES  
(
 input1  ,
    input2  ,
    input3  ,
    input4  ,
    input5  ,
    input6  ,
    input7  ,
    input8  ,
    input9  ,
    input10  ,
    input11  ,
    input12  ,
    input13  ,
    input14  ,
    input15  ,
    input16  ,
    input17  ,
    input18  ,
    input19  ,
    input20  ,
    input21  ,
    input22  ,
    input23  ,
    input24  ,
    input25  ,
    input26  ,
    input27  ,
    input28  ,
    input29  ,
    input30  ,
    input31  ,
    input32  ,
    input33  ,
    input34  ,
    input35  ,
    input36  ,
    input37  ,
    input38  ,
    input39  ,
    input40  ,
    input41  ,
    input42  ,
    input43  ,
    input44  ,
    input45  ,
    input46  ,
    input47  ,
    input48  ,
    input49  ,
    
    ideal1  ,
    ideal2  ,
    ideal3  ,
    ideal4  ,
    ideal5  ,
    ideal6  ,
    ideal7  ,
    ideal8  ,
    ideal9  ,
    ideal10  ,
    ideal11  ,
    ideal12  ,
    ideal13  ,
    ideal14  ,
    ideal15  ,
    ideal16  ,
    ideal17  ,
    ideal18  ,
    ideal19  ,
    ideal20  ,
    ideal21  ,
    ideal22  ,
    ideal23  ,
    ideal24  ,
    ideal25  ,
    ideal26  ,
    ideal27  ,
    ideal28  ,
    ideal29  ,
    ideal30  ,
    ideal31  ,
    ideal32  ,
    ideal33  ,
    ideal34  ,
    ideal35  ,
    ideal36  ,
    ideal37  ,
    ideal38  ,
    ideal39  ,
    ideal40  ,
    ideal41  ,
    ideal42  ,
    ideal43  ,
    ideal44  ,
    ideal45  ,
    ideal46  ,
    ideal47  ,
    ideal48  ,
    ideal49    

) ;

LOAD DATA INFILE 'D:\\sayisalAi\\inp6_12li.csv' INTO TABLE lotoresults6_12
  FIELDS TERMINATED BY ',' 
  LINES TERMINATED BY '\r\n'
IGNORE 1 LINES  
(
 input1  ,
    input2  ,
    input3  ,
    input4  ,
    input5  ,
    input6 ,
	 ideal1,
    ideal2 ,
    ideal3 ,
    ideal4 ,
    ideal5 ,
    ideal6  ,
    ideal7 ,
    ideal8 ,
    ideal9 ,
    ideal10 ,
    ideal11,
    ideal12  
) ;

